apiVersion: v1
kind: Pod
metadata:
  name: never-pod
spec:
  containers:
    - name: failing-container
      image: busybox:latest
      ports:
        - containerPort: 80
      command: ["/bin/sh", "-c", "sleep 10; exit 1"] # 비정상 종료
  restartPolicy: Never