apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ddoddo-market-chart.fullname" . }}-db-secret
  labels: {{- include "ddoddo-market-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  POSTGRES_DB: {{ .Values.database.name | quote }}